# Generated by Django 5.2.4 on 2025-07-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_make',
        ),
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
